### ISSUE TITLE
No module named 'loopy.target.c.c_execution'

### ISSUE THREAD

**Issue by stgeke** [SLACKHA/pyJac#33]
Trying to run the latest master results in: 

from loopy.target.c.c_execution import CPlusPlusCompiler
ImportError: No module named 'loopy.target.c.c_execution'

Any idea how to fix this?

**Comment by arghdos** [comment]
Hi Stefan, can I assume you're attempting to use the version of [pyjac-V2](https://github.com/SLACKHA/pyJac-v2) for our [upcoming paper](https://arxiv.org/abs/1809.01029) that's online?  

The requirements / etc. on that repo were a bit out of date, but I just pushed an updated master branch that should have fixed a number of issues there.

I haven't created the documentation yet: the best docs for the equations evaluated are in the supplemental of the linked paper, and the _easiest_ way to get a working install up and running is:

A) If you need OpenCL support, use conda and roughly follow the build process in the [travis.yml](https://github.com/SLACKHA/pyJac-v2/blob/master/.travis.yml) file.

B) If you don't need OpenCL support, you _should_ be able to simply run:

`pip install -r requirements.txt`

This specific error indicates that the version of `loo.py` you have installed is too old (I forget which version I added the `c_execution` stuff in, but it was something like 2017.1).  You want `2018.1`, or the commit: https://github.com/inducer/loopy.git@049424df12da70a5ae8d2411c6d12dc2269ff626

**Comment by stgeke** [comment]
Just realized that it's turned on by default. Switching it off  results now in:
ImportError: ~/.local/lib/python2.7/site-packages/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf

**Comment by arghdos** [comment]
Ok, the problem here was that there was still some unguarded `pyopencl` references in the master branch.  The [most recent commit](https://github.com/SLACKHA/pyJac-v2/tree/d000b7df9e599b188b6b1c52cbb3fd9b93cb1865) should have resolved this.  You'll (likely) have to reinstall loo.py once more; there's a chance it will work as is, but currently I depend on a few features that are still waiting to be integrated into the master branch over there.  If you run into any loo.py errors, you should reinstall via my [working branch ('working2')](https://github.com/arghdos/loopy/tree/working2)
